@database = MECHAZON-DATABASE
@collection = employee-information

@domain = http://localhost

@port = 3000

###
GET {{domain}}:{{port}}/find/{{database}}/{{collection}}
Content-Type : application/json

###
POST {{domain}}:{{port}}/insert/{{database}}/{{collection}}
Content-Type: application/json
